# Generated by Django 4.1.3 on 2022-12-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='Возраст студента')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StudentToSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата зачисления на секцию')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m', to='section.section', verbose_name='Секция')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связь студента с секцией',
                'verbose_name_plural': 'Связи студентов с секциями',
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(related_name='student', through='student.StudentToSection', to='section.section', verbose_name='Посещаемые секции'),
        ),
    ]
